# Numpy 
It is similar to list. 

**Syntax**: - a=np.arange(6)

- Faster 
- Consume less memory
- One data type

**Array**: An array is central data type of the numpy Library. An array is a grid of values and it contains information about the row data, how to locate element, and how to interpret an element. The elements are all of the same type, referred as to the array dtype. An array of non-negative integers, by Boolean, by another array, or by integer. 

**Rank of An Array:** The rank of an array is the dimension of an array. 

**Shape of An Array:** The shape of an array is a tuple of Integers giving the size of the array along each dimension. 

**Tuple of Integers:**


- ### Array 

In [4]:
# Import numpy library
import numpy as np 

In [56]:
# defining and displaying array
a=np.array([5,5,5,5,5,5]) 
print("The Array we created is:",a)

The Array we created is: [5 5 5 5 5 5]


In [57]:
# Type of ann array
print("The Type of array is :", type(a))

The Type of array is : <class 'numpy.ndarray'>


In [45]:
# 2D array (list of list)
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
print(b, "The list of list is 2-D array")

[[5 5 5]
 [5 5 5]
 [5 5 5]] The list of list is 2-D array


- A **vector** is an array with single dimension (no difference between row and column vector). 

- A **matrix** refers to an array with two dimension.  
________

- ### 1-D Array

In [6]:
# Import numpy as np
import numpy as np

In [46]:
# defining and displaying array
a=np.array([6,6,6])
print(a, "The defined array" )

[6 6 6] The defined array


In [47]:
# Check type of array
print(type(a), "The type of our defined")

<class 'numpy.ndarray'> The type of our defined


In [49]:
# Length of array
print(len(a),"is the length of defined array")

3 is the length of defined array


In [64]:
# Indexing an array
print("The element at zero index is: ", a[0])
print("The element at 1 index is: ", a[1])
print("The element at 2 index is: ", a[2])
print("The whole array is : ", a[0:])

The element at zero index is:  6
The element at 1 index is:  6
The element at 2 index is:  6
The whole array is :  [6 6 6]


______

- ### 2-D Array

In [66]:
# import numpy module
import numpy as np 

In [53]:
# defining and displaying array 2D array (List of List)
b=np.array([[7,7,7],[8,8,8],[9,9,9]])
print (b, ": The 2-D array")

[[7 7 7]
 [8 8 8]
 [9 9 9]] : The 2-D array


In [69]:
# Checking the type 
print("The type of array is: ",type(b))

The type of array is:  <class 'numpy.ndarray'>


In [70]:
# Length of array
print("The length of array is: ", len(b))

The length of array is:  3


In [71]:
# Indexing of array
print("The elements of array at index 1 is : ", b[1])

The element of array at index 1 is :  [8 8 8]


In [51]:
# Whole array
print(b[0:], ": Indexed array ")

[[5 5 5]
 [5 5 5]
 [5 5 5]] : Indexed array 


_____

# 3-D array

For **3-D higher dimensional array**, the term tensor is also used. The dimension are called axis. 

**Tensoflow**: is free and open source software library for machine learning and artificial intelligence.

Creating an array and other details...

In [1]:
# import numpy library
import numpy as np 

In [50]:
# defining and displaying 3D array
c=np.array([[[2,2,2],[1,1,1]]])
print(c, ": The 3D array we created")

[[[2 2 2]
  [1 1 1]]] : The 3D array we created


In the above array we have **2-axis:** 

- **First axis:** has length 2, which means that it contain 2,2 elements from top to bottom.

- **Second axis:** has length 3, which means that it contain 3,3 elements from left to right.  

____

- **Array by other commands**

In [5]:
# Arrays of zeros of 2 zeros
b=np.zeros(2)
print("The one dimensional array containing 2 zeros elements: ",b)

The one dimensional array containing 2 zeros elements:  [0. 0.]


In [6]:
# Array of three ones 
c=np.ones(3)
print("The one dimensional array containing 3 ones elements: ",c)

The one dimensional array containing 3 ones elements:  [1. 1. 1.]


In [7]:
# Creating an empty array
d=np.empty(2)
print("An empty 1 D array containing two zeros:", d)

An empty 1 D array containing two zeros: [0. 0.]


In [13]:
r=np.empty(3)
print("An empty 1 D array containing four zeros:", r)
# this need clarification 

An empty 1 D array containing four zeros: [1. 1. 1.]


In [19]:
# Array with range of elements
f=np.arange(6)
print("The array of 6 elements : =>", f, ". In python the last term is exclusive")

The array of 6 elements : => [0 1 2 3 4 5] . In python the last term is exclusive


In [23]:
# Creating array with specific range (from - to)
g=np.arange(2,20)
print("An array from range 2 to 20 is : ", g, ". Last term is exclusive in python")

An array from range 2 to 20 is :  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] . Last term is exclusive in python


In [24]:
# Creating array with specific interval between elements
h=np.arange(2,20,2)
print("An array from 2 to 20 with interval between each two terms are 2 is : ",h,". Last term is exclusive")

An array from 2 to 20 with interval between each two terms are 2 is :  [ 2  4  6  8 10 12 14 16 18] . Last term is exclusive


In [26]:
# Linearly spaced array
i=np.linspace(0,10,num=5)   # num means contains 5 elements
print("Linearly spaced array from zero to 10 is containing 5 numbers is : ", i,)

Linearly spaced array from zero to 10 is containing 5 numbers is :  [ 0.   2.5  5.   7.5 10. ]


In [37]:
# Specific data type in array
j=np.ones(5, dtype=np.int8)
print("The array of 5 ones with dtype int8 is : ", j)
print("type of array is : ", type(j))

The array of 5 ones with dtype int8 is :  [1 1 1 1 1]
type of array is :  <class 'numpy.ndarray'>


In [38]:
k=np.ones(3, dtype=np.float64)
k
# Google the types 

array([1., 1., 1.])

In [39]:
# 2-D array of zeros 
l=np.zeros((3,4))
print("2-D array of zeros is : ", l, ". enclosed in [[]]")

2-D array of zeros is :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] . enclosed in [[]]


In [40]:
m=np.ones((5,6))
print("2-D array of ones is : ", m, ". enclosed in [[]]")

2-D array of ones is :  [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] . enclosed in [[]]


In [41]:
o=np.empty((3,4))
print("2-D an empty array is : ", o, ". enclosed in [[]]")

2-D an empty array is :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] . enclosed in [[]]


In [44]:
# Creating and reshaping 3D array
p=np.arange(24).reshape(2,3,4)  # contain 24 elements in shape 2 3 4 dimensions 
print(p, "Reshaped 3-D array into 2 3 4 is :" )

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] Reshaped 3-D array into 2 3 4 is :


_____________________
### Numpy Library practice...

In [49]:
# Import numpy library
import numpy as np

In [50]:
# defining array with name 
food=np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [51]:
# defining array with name 
prices=np.array([350,460,210])
prices

array([350, 460, 210])

+ We can check types, lengths and indexing of the array as mentioned above... 

In [52]:
# calculating the mean of the prices 
prices.mean()

340.0

- ### Array Functions

In [59]:
# Lets create an array
a=np.array([10.2, 30.7, 6,8, 94,5])
a

array([10.2, 30.7,  6. ,  8. , 94. ,  5. ])

In [60]:
# Sorting the array in an ascending order
a.sort()
a

array([ 5. ,  6. ,  8. , 10.2, 30.7, 94. ])

In [61]:
# Creating another array
b=np.array([20.3, 54, 67, 8.9, 510])
b 

array([ 20.3,  54. ,  67. ,   8.9, 510. ])

In [62]:
import numpy as np
# Concatenating a and b arrays 
c=np.concatenate((a,b))
c 

array([  5. ,   6. ,   8. ,  10.2,  30.7,  94. ,  20.3,  54. ,  67. ,
         8.9, 510. ])

In [63]:
# creating two arrays for further drill
a=np.array([[1,2],[5,4]])
b=np.array([[6,7],[8,9]])

In [59]:
# Vertical Concatenation 
c=np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [64]:
# Horizontal Concatenation 
c=np.concatenate((a,b), axis=1)
c
# dimensions must be equal but google for unequal dimensional array concatenating the array. 

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [7]:
# Creating three dimensional array
a=np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [67]:
# To find/ check the dimensions of the above array
print("The dimension of the above created array 'a' is :", a.ndim)

The dimension of the above created array 'a' is : 3


In [68]:
# defining and displaying array
b=np.array([[1,2,3],[5,6,7],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 11, 12]])

In [69]:
# checking the dimensions
print("The dimension of the above created array 'a' is :",b.ndim)

The dimension of the above created array 'a' is : 2


In [9]:
# defining array of eigth element between 0 to 10 having equal interval. 
e=np.linspace(0,10, num=8)
e
# change the value of num 

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [8]:
# Checking the array size 
print("The size of an array 'a' is :", a.size)

The size of an array 'a' is : 24


In [9]:
# Finding the shape 
print("The shape of an array 'a' is :", a.shape)

The shape of an array 'a' is : (3, 2, 4)


In [10]:
# define 3-D array
q=np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
print(q, ": the 3-D array we defined.")

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]] : the 3-D array we defined.


In [11]:
print("The shape of our defined array q is : ", q.shape)

The shape of our defined array q is :  (3, 2, 4)


In [15]:
# changing the shape of array from q to q1
q1=np.reshape(q, newshape=(4,6), order="A")    # order only ka take (A, C, F)
print(q1, " : is our new define array from q.")
# need proper study to check every thing 

[[0 1 2 3 4 5]
 [6 7 0 1 2 3]
 [4 5 6 7 0 1]
 [2 3 4 5 6 7]]  : is our new define array from q.


In [18]:
print("The shape of our new defined array from q to q1 is : ",q1.shape, ". Which is changed, you can see above.")

The shape of our new defined array from q to q1 is :  (4, 6) . Which is changed, you can see above.


In [19]:
# changing the shape of array from q to q2 
q2=np.reshape(q, newshape=(3,8), order="A")    # order only ka take (A, C, F)
print(q2, " : is our new define array from q.")
# need proper study to check every thing 

[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]  : is our new define array from q.


In [20]:
print("The shape of our new defined array from q to q2 is : ",q2.shape, ". Which is changed, you can see above.")

The shape of our new defined array from q to q2 is :  (3, 8) . Which is changed, you can see above.


- **Convert 1-D array to 2-D array => Row-wise conversion**

In [38]:
# defining 1-D array
a=np.array([1,2,3,4,5,6,7,8,9])
print("1-D array:",a, ". Eclosed in []s")

1-D array: [1 2 3 4 5 6 7 8 9] . Eclosed in []s


In [43]:
# row wise 2D Conversion 
b=a[np.newaxis,:]
print("Row-Wise Converted Array:", b, ". Enclosed in [[]]s")

Row-Wise Converted Array: [[1 2 3 4 5 6 7 8 9]] . Enclosed in [[]]s


- **Convert 1-D array to 2-D array => Column-wise conversion**

In [44]:
# create an array
d=np.array([1,2,3,4,5,6,7,8,9])
print("1-D array:",d, ". Eclosed in []s")

1-D array: [1 2 3 4 5 6 7 8 9] . Eclosed in []s


In [41]:
# Column wise 2D Conversion 
e=a[:,np.newaxis]
print("Column-Wise Converted Array:", e, "Enclosed in [[]]s")

Column-Wise Converted Array: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] Enclosed in [[]]s


- **Slicing of Array**

In [23]:
# Creating 1-D dimensional array
a=np.array([1,2,3,4,5,6,7,12,16,100])
print(a, ". The array we created.")

[  1   2   3   4   5   6   7  12  16 100] . The array we created.


In [25]:
# slicing the array
a[2:6]  # from 2 to 6, it may any digits 
print(a[2:6], ". The array is sliced. The last digit in Python is exclusive:")

[3 4 5 6] . The array is sliced. The last digit in Python is exclusive:


In [55]:
# slicing the array
a[1:8]  # from 2 to 6, it may any digits 
print("The last digit in Python is exclusive:",a[1:8])

The last digit in Python is exclusive: [ 2  3  4  5  6  7 12]


_______________
- Arithmatic Operations and Array

In [28]:
# Multiplication, addition, a,sum, and a.mean 
f=a*6
g=a+6
print("Multiplication of 6 with array 'a', f=",f)
print("Each factor got multiplied with 6.")
print("Addition of 6 with array 'a', g=",g)
print("Each factor got increased with 6.")

Multiplication of 6 with array 'a', f= [  6  12  18  24  30  36  42  72  96 600]
Each factor got multiplied with 6.
Addition of 6 with array 'a', g= [  7   8   9  10  11  12  13  18  22 106]
Each factor got increased with 6.


In [29]:
# to add all elements of array a 
print(a.sum(),": is the sum of all elements of the array 'a'")

156 : is the sum of all elements of the array 'a'


In [31]:
# to add all elements of array a 
print(a.mean(),": is the mean of of the array 'a'.")

15.6 : is the mean of of the array 'a'.
